### ISSUE TITLE
Transaction not going through

### ISSUE THREAD

**Issue by dekacypher** [noahtheprogrammer/merxbot#27]
Hi, I'm running your sell.py file and the transaction isn't going through, I've done som changes like using raydium instead of Jupiter since it doesn't have coin i'm using it on $MAGA. I've integrated a limit buy and sell order.  

```

SOL_MINT_ADDRESS = "So11111111111111111111111111111111111111112"
SOL_DECIMALS = 9

def get_pool_id(token_address):
    url = f"https://api.raydium.io/v2/ammV3/ammPools"
    response = requests.get(url)
    if response.status_code == 200:
        response = response.json()
        #print(response)
    for pool in response['data']:
        if pool["mintA"] == token_address:
            return pool["id"]
        elif pool["mintB"] == token_address:
            return pool["id"]


# Returns the route to be manipulated in createTransaction()
async def create_exchange(input_amount: int, input_token_mint: str, mode : str) -> dict:
    symbol = getSymbol(input_token_mint)
    log_transaction.info(f"Soltrade is creating exchange for {input_amount} dollars in {symbol}")
    sol_mint = "So11111111111111111111111111111111111111112"

    token_decimals = await get_token_decimals(input_token_mint)
    # Determines what mint address should be used in the api link
    if mode == "buy" and input_token_mint == sol_mint:
        output_token_mint = configs["other_mint"]
  
    elif mode == "sell":
        output_token_mint = sol_mint
        print(f"Output Token decimals for SELL: {output_token_mint}")
    
    #Calculate amount in smallest unit
    amount_in = int(input_amount * token_decimals)
    
    pool_id = get_pool_id(input_token_mint)
    print(f"Pool ID: {pool_id}")
     # Create the swap transaction using Raydium API
    api_link = f"https://api.raydium.io/v2/swap?poolId={pool_id}"
    params = {
        "inputMint": input_token_mint,
        "outputMint": output_token_mint,
        "amount": amount_in,
        "slippage": configs['slippage']
    }

    async with httpx.AsyncClient() as client:
        response = await client.get(api_link, params=params)
        exchange_data = response.json()
        pprint(f"EXCHANGE CREATED:\n{exchange_data}")
        return exchange_data


# Returns the swap_transaction to be manipulated in sendTransaction()
async def create_transaction(quote: dict, input_token_mint, output_token_mint) -> dict:
    log_transaction.info(f"""Soltrade is creating transaction for the following quote: 
{quote}""")

    if 'error' in quote:
        log_transaction.error(f"Error in quote: {quote['error']}")
        raise Exception(f"Error in quote: {quote['error']}")

    pool_id = get_pool_id(input_token_mint)
    #pool_id = "9XsGAA3xHC6gqRgThRrcaUPU6jzerZacWgfyMb17579t"

    # Parameters used for the Raydium POST request
    parameters = {
        "quoteResponse": quote,
        "userPublicKey": str(configs['public_address']),
        "wrapUnwrapSOL": True,
        "computeUnitPriceMicroLamports": 20 * 300_000  # fee of roughly $.04  :shrug:
    }
    #9XsGAA3xHC6gqRgThRrcaUPU6jzerZacWgfyMb17579t
    # Returns the JSON parsed response of Jupiter
    async with httpx.AsyncClient() as client:
        response = await client.post(f"https://api.raydium.io/v2/swap?poolId={pool_id}", json=parameters)
        exchange_data = response.json()

        pprint(f"TRANSACTION CREATE:\n{exchange_data}")
        return exchange_data

# Uses the previous functions and parameters to exchange Solana token currencies
async def perform_swap(sent_amount: float, price_limit, sent_token_mint: str, mode : str):
    global position
    log_general.info("Soltrade is taking a limit position.")

    #TODO: fetch the current price and create a limit order
    current_price = get_price(sent_token_mint)

    base_token = await get_token_decimals(sent_token_mint)
    quote = trans = opts = txid = tx_error = None
    is_tx_successful = False

    for i in range(0,3):
        if not is_tx_successful:
            try:
                if (mode == "buy" and round(current_price,3) <= price_limit) or (mode == "sell" and round(current_price,3) >= price_limit):
                    quote = await create_exchange(sent_amount, sent_token_mint, mode)
                    trans = await create_transaction(quote, sent_token_mint, SOL_MINT_ADDRESS)
                    print(f"TRANS:\n{trans}")
                    opts = TxOpts(skip_preflight=False, preflight_commitment="confirmed", last_valid_block_height=find_last_valid_block_height())
                    txid = send_transaction(trans["swapTransaction"], opts)

                    for i in range(3):
                        await asyncio.sleep(35)
                        tx_error = find_transaction_error(txid)
                        if not tx_error:
                            is_tx_successful = True
                            break
                else:
                    log_general.info(f"Price hasn't reached {price_limit}. Waiting for the next opportunity.")
                    await asyncio.sleep(60)
                    current_price = get_price(sent_token_mint)

            except Exception as e:
                if RPCException:
                    print(traceback.format_exc())
                    log_general.warning(f"Soltrade failed to complete transaction {i}. Retrying.")
                    continue
                else:
                    raise
            for i in range(0, 3):
                try:
                    await asyncio.sleep(35)
                    tx_error = find_transaction_error(txid)
                    if not tx_error:
                        is_tx_successful = True
                        break
                except TypeError as e:
                    print(traceback.format_exc())
                    log_general.warning("Soltrade failed to verify the existence of the transaction. Retrying.")
                    continue
        else:
            break

    if tx_error or not is_tx_successful:
        print(traceback.format_exc())
        log_general.error("Soltrade failed to complete the transaction due to slippage issues with Raydium.")
        return False

    # if sent_token_mint == SOL_MINT_ADDRESS:
    #     bought_amount = int(quote['outAmount']) / SOL_DECIMALS
    #     log_transaction.info(f"Sold {sent_amount} SOL for {bought_amount:.6f} {config().other_mint_symbol}")
    # else:
     
    return True

if __name__ == "__main__":
    configs = load_config()
    input_amount = 0.03 #SOL
    price_token = 0.005 
    asyncio.run(perform_swap(input_amount, price_token, configs["other_mint"], "sell"))
    
```
```
2024-05-26 21:07:55       Soltrade is taking a limit position.
Response: MAGA
2024-05-26 21:07:58       Soltrade is creating exchange for 0.03 dollars in ('MAGA', 'SOL')
Output Token decimals for SELL: So11111111111111111111111111111111111111112
Pool ID: 9XsGAA3xHC6gqRgThRrcaUPU6jzerZacWgfyMb17579t
('EXCHANGE CREATED:\n'
 "{'id': 'cb3f7e9f73ef4260bb8a4bde973fd7dd', 'success': False}")
2024-05-26 21:07:59       Soltrade is creating transaction for the following quote: 
{'id': 'cb3f7e9f73ef4260bb8a4bde973fd7dd', 'success': False}
('TRANSACTION CREATE:\n'
 "{'id': '48775008ab1343c2977b26b26764901c', 'success': False}")
TRANS:
{'id': '48775008ab1343c2977b26b26764901c', 'success': False}
Traceback (most recent call last):
  File "/Users/anon/soltrade-1/soltrade/transactions.py", line 204, in perform_swap
    txid = send_transaction(trans["swapTransaction"], opts)
KeyError: 'swapTransaction'

2024-05-26 21:08:01       Soltrade failed to complete transaction 0. Retrying.
Response: MAGA
2024-05-26 21:08:01       Soltrade is creating exchange for 0.03 dollars in ('MAGA', 'SOL')
Output Token decimals for SELL: So11111111111111111111111111111111111111112
Pool ID: 9XsGAA3xHC6gqRgThRrcaUPU6jzerZacWgfyMb17579t
('EXCHANGE CREATED:\n'
 "{'id': '82127ce8a99d4300ae8fe9775d916cf4', 'success': False}")
2024-05-26 21:08:02       Soltrade is creating transaction for the following quote: 
{'id': '82127ce8a99d4300ae8fe9775d916cf4', 'success': False}
('TRANSACTION CREATE:\n'
 "{'id': '03a5dafb4cf9461691a4ad89bad88639', 'success': False}")
TRANS:
{'id': '03a5dafb4cf9461691a4ad89bad88639', 'success': False}
Traceback (most recent call last):
  File "/Users/anon/soltrade-1/soltrade/transactions.py", line 204, in perform_swap
    txid = send_transaction(trans["swapTransaction"], opts)
KeyError: 'swapTransaction'

2024-05-26 21:08:03       Soltrade failed to complete transaction 1. Retrying.
Response: MAGA
2024-05-26 21:08:03       Soltrade is creating exchange for 0.03 dollars in ('MAGA', 'SOL')
Output Token decimals for SELL: So11111111111111111111111111111111111111112
Pool ID: 9XsGAA3xHC6gqRgThRrcaUPU6jzerZacWgfyMb17579t
('EXCHANGE CREATED:\n'
 "{'id': '083f18c959e04c55857cda68a4bb5588', 'success': False}")
2024-05-26 21:08:05       Soltrade is creating transaction for the following quote: 
{'id': '083f18c959e04c55857cda68a4bb5588', 'success': False}
('TRANSACTION CREATE:\n'
 "{'id': '2b234893fdb74fda8294ccc225b06a41', 'success': False}")
TRANS:
{'id': '2b234893fdb74fda8294ccc225b06a41', 'success': False}
Traceback (most recent call last):
  File "/Users/anon/soltrade-1/soltrade/transactions.py", line 204, in perform_swap
    txid = send_transaction(trans["swapTransaction"], opts)
KeyError: 'swapTransaction'

2024-05-26 21:08:07       Soltrade failed to complete transaction 2. Retrying.
NoneType: None
2024-05-26 21:08:07       Soltrade failed to complete the transaction due to slippage issues with Raydium.
```

**Comment by nmweaver** [comment]
@dekacypher it appears that you are attempting to send a transaction while still using Jupiter's API, which is why you continue to receive a `KeyError` whenever the program is executed. I would recommend changing from `swapTransaction` used in `send_transaction()` to the Raydium equivalent. It looks like you're onto something, so I would recommend maybe creating a pull request once you have something up and running.

**Comment by dekacypher** [comment]
Hi, I managed to solve this by using the Jupiter API instead of Raydium.

Raydium API is a bit tricky as I couldn’t find any proper documentation for python, so I did this instead:


    https://quote-api.jup.ag/v6/quote?inputMint={input_token_mint}&outputMint={output_token_mint}&amount={int(amount_in)}&slippageBps={config().slippage}

This in `create_transaction()`:

     https://quote-api.jup.ag/v6/swap

**Comment by nmweaver** [comment]
@dekacypher looking good! Would you perhaps be willing to create a pull request?

**Comment by dekacypher** [comment]
I believe in your code, you're already using Jupiter API and the links i added, I just happened to switch to Raydium api as I encountered a problem with Jupiter, not sure what it was. However, apparently I solved it.

I haven't added something new to the code, so I don't think there's any need to make a pull request.
